# Generated by Django 4.0.4 on 2022-12-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('poster', models.URLField()),
                ('genres', models.CharField(max_length=200)),
            ],
        ),
    ]
