# Generated by Django 4.0.4 on 2023-01-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0003_newuser_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='userId',
            field=models.AutoField(default=950, primary_key=True, serialize=False),
        ),
    ]
