# Generated by Django 4.0.4 on 2023-01-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
