# Generated by Django 4.0.4 on 2023-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0008_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
