# Generated by Django 4.0.4 on 2023-01-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0011_regform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegForm',
        ),
    ]
