# Generated by Django 4.0.4 on 2023-01-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegForm',
        ),
    ]
